codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "src/types/**/*"
  - "**/*.types.ts"
  - "**/*.d.ts"
  - "dist/**/*"
