const commitAnalyzer = [
  '@semantic-release/commit-analyzer',
  {
    releaseRules: [
      { type: 'fix', release: 'patch' },
      { type: 'perf', release: 'patch' },
      { type: 'chore', release: 'patch' },
      { type: 'docs', release: 'patch' },
      { type: 'style', release: 'patch' },
      { type: 'refactor', release: 'patch' }
    ]
  }
];

const fullPlugins = [
  commitAnalyzer,
  '@semantic-release/release-notes-generator',
  '@semantic-release/changelog',
  '@semantic-release/npm',
  [
    '@semantic-release/git',
    {
      assets: ['package.json', 'package-lock.json', 'CHANGELOG.md'],
      message:
        'chore(release): v${nextRelease.version}\n\nAutomatically generated by semantic release [skip ci]'
    }
  ],
  [
    '@semantic-release/github',
    {
      assets: ['dist/**/*'],
      releaseName: 'v${nextRelease.version}'
    }
  ]
];

const versionOnlyPlugins = [commitAnalyzer];

export default {
  branches: ['main'],
  plugins:
    process.env.SEMANTIC_RELEASE_VERSION_ONLY === 'true'
      ? versionOnlyPlugins
      : fullPlugins,
  tagFormat: 'v${version}'
};
