name: Package Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git for SSH signing
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save the private key from GitHub secret to a file
          echo "${{ secrets.GALILEO_AUTOMATION_SSH_PRIVATE_KEY }}" > ~/.ssh/galileo_signing_key
          chmod 600 ~/.ssh/galileo_signing_key

          # Configure Git to use the SSH key file
          git config --global gpg.format ssh
          git config --global user.signingKey ~/.ssh/galileo_signing_key
          git config --global commit.gpgsign true
          git config --global user.email ci@rungalileo.io
          git config --global user.name "galileo-automation"

      - name: Semantic Release (bump version + publish + Github release)
        uses: cycjimmy/semantic-release-action@v4
        with:
          ci: false
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GALILEO_AUTOMATION_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
